TradeProducerConsumerGroup = 'TradeProducer'
ProductID = 'BTC/USD'
KrakenWebSocketChannel = 'trade'
KrakenWebSocketURL = 'wss://ws.kraken.com/v2'
KafkaBrokerAddress = 'redpanda-0:9092'
KafkaInputTopic = 'Trades'
